CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(225) NOT NULL,
    manufacturer VARCHAR(225) NOT NULL,
    model VARCHAR(225) NOT NULL,
    sw_ver VARCHAR(225) NOT NULL,
    identifier VARCHAR(225) UNIQUE NOT NULL,
    connections JSONB NOT NULL DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS device_entities (
    id TEXT PRIMARY KEY,
    type VARCHAR(225) NOT NULL,
    name VARCHAR(225) NOT NULL,
    features VARCHAR[],
    device_id UUID NOT NULL,
    module TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device
      FOREIGN KEY(device_id) 
	  REFERENCES devices(id)
);

CREATE TABLE IF NOT EXISTS entity_states (
    value JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    entity_id TEXT NOT NULL,
    CONSTRAINT fk_entity
      FOREIGN KEY(entity_id) 
	  REFERENCES device_entities(id)
);